Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "192.168.56.200"
  config.vm.synced_folder "develop/", "/srv/develop" 
  config.vm.provision "shell", inline: <<-SHELL
    apt-get install cargo -y
  SHELL
end
